### ISSUE TITLE
prefersNavigationBarHidden = true 

### ISSUE THREAD

**Issue by HZRZCW** [zjinhu/SwiftBrick#1]
设置prefersNavigationBarHidden = true  ，在组件化项目中无效(SwiftMediator demo 中设置无效，SwiftBrick demo 设置有效！)，在非组件化架构项目有效。

**Comment by zjinhu** [comment]
需要交互那个方法在APP启动是执行一下，以前iOS13之前可以启动自动交换，后来系统更新方法没了，需要手动调一下
SwiftBrick.navBarSmooth()
然后就可以执行了

**Comment by HZRZCW** [comment]
完美
